name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Lint
        run: ./gradlew ktlintCheck
      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar
      - name: Create kpcli.bat
        run: |
          @echo off
          set currentDir=%cd%
          cd /d %~dp0
          java -jar kpcli-all.jar %currentDir%\
      - name: Create release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}